# Generated by Django 4.0.1 on 2022-07-14 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trick',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserTrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('passed', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(choices=[(1, 'Cobblestone'), (2, 'Coal'), (3, 'Iron'), (4, 'Redstone'), (5, 'Gold'), (6, 'Diamond')], default=1)),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trick', to='tricks.trick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trick', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
