# Generated by Django 4.0.1 on 2022-01-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tricks.trick')),
            ],
        ),
    ]
