# Generated by Django 4.0.1 on 2022-01-21 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tricks', '0003_trick_created_trick_modified_tutorial_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('passed', models.DateTimeField(blank=True, null=True)),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tricks.trick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
