# Generated by Django 4.0.1 on 2022-01-21 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tricks', '0004_usertrick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrick',
            name='trick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tricks.trick'),
        ),
        migrations.AlterField(
            model_name='usertrick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to=settings.AUTH_USER_MODEL),
        ),
    ]
