# Generated by Django 4.0.1 on 2022-02-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0005_alter_usertrick_trick_alter_usertrick_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrick',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Cobblestone'), (2, 'Coal'), (3, 'Silver'), (4, 'Redstone'), (5, 'Gold'), (6, 'Diamond')], default=1),
        ),
    ]
