# Generated by Django 4.0.1 on 2022-07-10 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tricks', '0006_usertrick_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrick',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Cobblestone'), (2, 'Coal'), (3, 'Iron'), (4, 'Redstone'), (5, 'Gold'), (6, 'Diamond')], default=1),
        ),
        migrations.AlterField(
            model_name='usertrick',
            name='trick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trick', to='tricks.trick'),
        ),
        migrations.AlterField(
            model_name='usertrick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trick', to=settings.AUTH_USER_MODEL),
        ),
    ]
