# Generated by Django 4.0 on 2022-01-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('b', 'beginner'), ('i', 'intermediate'), ('a', 'advanced'), ('o', 'other')], default='other', max_length=1)),
                ('official', models.BooleanField(default=False)),
            ],
        ),
    ]
