# Generated by Django 4.0.1 on 2022-07-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tricks', '0002_trick_created_trick_modified_usertrick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('yt_title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tricks.trick')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
